name: JS Actions
on: 
  # pull_request:
  #   types: [labeled]
  push:
jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - name: saludo
        run: echo "Hola Mundo"
      # - uses: actions/checkout@v1
      # - name: hello-action
      #   uses: ./.github/actions/hello_world