name: JS Actions
on: 
  # pull_request:
  #   types: [labeled]
  push:
jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - name: saludo
        run: |
          echo "Hola Mundo"
          pwd
          ls -l
  # action2:
  #   runs-on: windows-latest
  #   steps:
  #     - name: saludo-windows
  #       run: echo "Hola en windows"
      # - uses: actions/checkout@v1
      # - name: hello-action
      #   uses: ./.github/actions/hello_world